# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParticleUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 1181)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(10, 10, 921, 751))
        self.Image.setAutoFillBackground(False)
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("../../../../Pictures/1500737818.jpg"))
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")

        self.BackgroundSlide = QtWidgets.QSlider(self.centralwidget)
        self.BackgroundSlide.setGeometry(QtCore.QRect(130, 831, 301, 21))
        self.BackgroundSlide.setOrientation(QtCore.Qt.Horizontal)
        self.BackgroundSlide.setObjectName("BackgroundSlide")

        self.AdaptiveSlide = QtWidgets.QSlider(self.centralwidget)
        self.AdaptiveSlide.setGeometry(QtCore.QRect(130, 880, 301, 21))
        self.AdaptiveSlide.setOrientation(QtCore.Qt.Horizontal)
        self.AdaptiveSlide.setObjectName("AdaptiveSlide")

        self.PeakSlide = QtWidgets.QSlider(self.centralwidget)
        self.PeakSlide.setGeometry(QtCore.QRect(130, 931, 301, 21))
        self.PeakSlide.setOrientation(QtCore.Qt.Horizontal)
        self.PeakSlide.setObjectName("PeakSlide")

        self.horizontalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(590, 830, 331, 22))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")

        self.MeanSlide = QtWidgets.QSlider(self.centralwidget)
        self.MeanSlide.setGeometry(QtCore.QRect(590, 880, 331, 22))
        self.MeanSlide.setOrientation(QtCore.Qt.Horizontal)
        self.MeanSlide.setObjectName("MeanSlide")

        self.horizontalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(590, 930, 331, 22))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")

        self.Update = QtWidgets.QPushButton(self.centralwidget)
        self.Update.setGeometry(QtCore.QRect(60, 990, 171, 41))
        self.Update.setObjectName("Update")

        self.ShowContours = QtWidgets.QPushButton(self.centralwidget)
        self.ShowContours.setGeometry(QtCore.QRect(250, 990, 171, 41))
        self.ShowContours.setCheckable(True)
        self.ShowContours.setChecked(True)
        self.ShowContours.setObjectName("ShowContours")

        self.CalculateParticles = QtWidgets.QPushButton(self.centralwidget)
        self.CalculateParticles.setGeometry(QtCore.QRect(120, 1060, 241, 61))
        self.CalculateParticles.setObjectName("CalculateParticles")

        self.ShowOriginal = QtWidgets.QPushButton(self.centralwidget)
        self.ShowOriginal.setGeometry(QtCore.QRect(10, 760, 171, 31))
        self.ShowOriginal.setObjectName("ShowOriginal")

        self.BackgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.BackgroundLabel.setGeometry(QtCore.QRect(10, 830, 111, 16))
        self.BackgroundLabel.setObjectName("BackgroundLabel")

        self.AdaptiveLabel = QtWidgets.QLabel(self.centralwidget)
        self.AdaptiveLabel.setGeometry(QtCore.QRect(10, 880, 111, 16))
        self.AdaptiveLabel.setObjectName("AdaptiveLabel")

        self.MeanLabel = QtWidgets.QLabel(self.centralwidget)
        self.MeanLabel.setGeometry(QtCore.QRect(460, 880, 101, 16))
        self.MeanLabel.setObjectName("MeanLabel")

        self.PeaksLabel = QtWidgets.QLabel(self.centralwidget)
        self.PeaksLabel.setGeometry(QtCore.QRect(10, 930, 111, 16))
        self.PeaksLabel.setObjectName("PeaksLabel")

        self.ParticleAproxLabel = QtWidgets.QLabel(self.centralwidget)
        self.ParticleAproxLabel.setGeometry(QtCore.QRect(550, 1020, 121, 20))
        self.ParticleAproxLabel.setObjectName("ParticleAproxLabel")

        self.ParticleDistanceLabel = QtWidgets.QLabel(self.centralwidget)
        self.ParticleDistanceLabel.setGeometry(QtCore.QRect(550, 1050, 111, 16))
        self.ParticleDistanceLabel.setObjectName("ParticleDistanceLabel")

        self.ParticleSizeBox = QtWidgets.QTextEdit(self.centralwidget)
        self.ParticleSizeBox.setGeometry(QtCore.QRect(680, 1020, 51, 21))
        self.ParticleSizeBox.setObjectName("ParticleSizeBox")

        self.DistanceBox = QtWidgets.QTextEdit(self.centralwidget)
        self.DistanceBox.setGeometry(QtCore.QRect(680, 1050, 51, 21))
        self.DistanceBox.setObjectName("DistanceBox")

        self.ParticleTemplate = QtWidgets.QLabel(self.centralwidget)
        self.ParticleTemplate.setGeometry(QtCore.QRect(760, 990, 111, 111))
        self.ParticleTemplate.setText("")
        self.ParticleTemplate.setPixmap(QtGui.QPixmap("../../../../Pictures/s-l300 (2).png"))
        self.ParticleTemplate.setScaledContents(True)
        self.ParticleTemplate.setObjectName("ParticleTemplate")

        self.TemplateLabel = QtWidgets.QLabel(self.centralwidget)
        self.TemplateLabel.setGeometry(QtCore.QRect(770, 1100, 91, 16))
        self.TemplateLabel.setObjectName("TemplateLabel")

        self.MeanLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.MeanLabel_2.setGeometry(QtCore.QRect(460, 830, 101, 16))
        self.MeanLabel_2.setObjectName("MeanLabel_2")
        self.MeanLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.MeanLabel_3.setGeometry(QtCore.QRect(460, 930, 101, 16))
        self.MeanLabel_3.setObjectName("MeanLabel_3")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 760, 221, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 760, 221, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(710, 760, 221, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 770, 47, 13))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 947, 21))
        self.menubar.setObjectName("menubar")
        self.menuinterfaceParticles = QtWidgets.QMenu(self.menubar)
        self.menuinterfaceParticles.setObjectName("menuinterfaceParticles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuinterfaceParticles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Update.setText(_translate("MainWindow", "Update Image"))
        self.ShowContours.setText(_translate("MainWindow", "Show Contours"))
        self.CalculateParticles.setText(_translate("MainWindow", "Calculate  Particles"))
        self.ShowOriginal.setText(_translate("MainWindow", "Original"))
        self.BackgroundLabel.setText(_translate("MainWindow", "Background Thresh:"))
        self.AdaptiveLabel.setText(_translate("MainWindow", "Adaptive Thresh:"))
        self.MeanLabel.setText(_translate("MainWindow", "Mean (Reduce):"))
        self.PeaksLabel.setText(_translate("MainWindow", "Gradient Peaks:"))
        self.ParticleAproxLabel.setText(_translate("MainWindow", "Particle Size Aprox. (px)"))
        self.ParticleDistanceLabel.setText(_translate("MainWindow", "Particle Distance (px):"))
        self.ParticleSizeBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">20</p></body></html>"))
        self.DistanceBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">14</p></body></html>"))
        self.TemplateLabel.setText(_translate("MainWindow", "Particle Template"))
        self.MeanLabel_2.setText(_translate("MainWindow", "Lorem Ipsum"))
        self.MeanLabel_3.setText(_translate("MainWindow", "Lorem Ipsum"))
        self.pushButton.setText(_translate("MainWindow", "Background"))
        self.pushButton_2.setText(_translate("MainWindow", "Outer Particle Border"))
        self.pushButton_3.setText(_translate("MainWindow", "Inner Positions"))
        self.label.setText(_translate("MainWindow", "Filter:"))
        self.menuinterfaceParticles.setTitle(_translate("MainWindow", "interfaceParticles"))
